---
- hosts: "all"
  sudo: "yes"
  remote_user: "vagrant"

  tasks:
  - name: "Add Docker APT repository key"
    apt_key:
      keyserver: "p80.pool.sks-keyservers.net"
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      state: "present"

  - name: "Add Docker APT repository for Trusty"
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
      state: "present"

  - name: "Install recommended packages"
    apt:
      name: "{{ item }}"
      state: "present"
      update_cache: "yes"
    with_items:
    - linux-image-extra-3.13.0-96-generic 
    - linux-image-extra-virtual

  - name: "Install unzip and Docker packages"
    apt:
      name: "{{ item }}"
      state: "present"
    with_items:
    - docker-engine
    - unzip
    - ethtool
    - bridge-utils

  - name: "Customize Docker daemon configuration"
    lineinfile:
      dest: "/etc/default/docker"
      regexp: "^#DOCKER_OPTS"
      line: "DOCKER_OPTS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'"
      owner: "root"
      group: "root"
      mode: "0644"
    
  - name: "Start Docker service"
    service:
      name: "docker"
      state: "started"

  - name: "Copy support files"
    copy:
      src: "{{ item }}"
      dest: "/home/vagrant"
      owner: "vagrant"
      group: "vagrant"
    with_items:
      - docker-setup.sh
      - docker-aliases
      - demo-docker-basic.sh
      - demo-docker-network.sh
      - demo-docker-swarm-01.sh
      - demo-docker-swarm-02.sh

  - name: "Make scripts executable"
    file:
      path: "{{ item }}"
      mode: "0755"
    with_items:
      - docker-setup.sh
      - demo-docker-basic.sh
      - demo-docker-network.sh
      - demo-docker-swarm-01.sh
      - demo-docker-swarm-02.sh
