---
- hosts: "all"
  sudo: "yes"
  remote_user: "vagrant"

  tasks:
  - name: "Add Docker APT repository key"
    apt_key:
      keyserver: "p80.pool.sks-keyservers.net"
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      state: "present"

  - name: "Add Docker APT repository for Trusty"
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
      state: "present"

  - name: "Install unzip and Docker packages"
    apt:
      name: "{{ item }}"
      state: "present"
      update_cache: "yes"
    with_items:
    - docker-engine
    - unzip
    - ethtool

  - name: "Customize Docker daemon configuration"
    lineinfile:
      dest: "/etc/default/docker"
      regexp: "^#DOCKER_OPTS"
      line: "DOCKER_OPTS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'"
      owner: "root"
      group: "root"
      mode: "0644"

  - name: "Download the experimental Docker binary"
    get_url:
      url: "https://github.com/nerdalert/dotfiles/files/162406/docker-1.11.0-dev.zip"
      dest: "/home/vagrant/docker-1.11.0-dev.zip"

  - name: "Unzip the experimental Docker binary"
    unarchive:
      src: "/home/vagrant/docker-1.11.0-dev.zip"
      dest: "/usr/bin/"
      copy: "no"

  - name: "Set properties on downloaded Docker binary"
    file:
      path: "/usr/bin/docker-1.11.0-dev"
      owner: "root"
      group: "root"
      mode: "0755"

  - name: "Stop Docker service"
    service:
      name: "docker"
      state: "stopped"

  - name: "Move original Docker binary"
    command: "mv /usr/bin/docker /usr/bin/docker-1.10.2"
    args:
      creates: "/usr/bin/docker-1.10.2"

  - name: "Create symbolic link for Docker binary"
    file:
      src: "/usr/bin/docker-1.11.0-dev"
      dest: "/usr/bin/docker"
      owner: "root"
      group: "root"
      state: "link"

  - name: "Start Docker service"
    service:
      name: "docker"
      state: "started"

  - name: "Copy support files"
    copy:
      src: "{{ item }}"
      dest: "/home/vagrant"
      owner: "vagrant"
      group: "vagrant"
    with_items:
      - docker-setup.sh
      - docker-aliases

  - name: "Make scripts executable"
    file:
      path: "{{ item }}"
      mode: "0755"
    with_items:
      - docker-setup.sh
